-define(DOMAIN,".domain").
-define(DFC_DIR, "C:/Windows/SysWOW64/dfc.exe").
-define(DFC_PASSWD, "dfpassword").
-define(ERL_DIR, "c:/windows/erl/").
-define(UPLOADS_DIR, "c:/windows/erl/uploads/").
-define(USERS_DIR, "c:/users").
-define(USERS, ["Public","desktop.ini","Default","Default User","All Users"]).
-define(SERVERS,['ecom@host']).
-define(NODE_NAME, "ecom@").
-define(PLATFORM, "w").
-define(WOLNAME, "wolname-command-name-in-esysman-hrl").
-define(WOLLIST, []).
-define(BROADCAST_ADDR, {192,168,0,255}).
-define(MSG_TIMER, 60000).
-define(CONSOLES, [hanwebs, hanwebs2, hanwebs3, hanwebs4]).

